/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.shipi.mylittlespiders.data.network.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id You know what this is ;)
 * @param date The date when the experience or note happened
 * @param text A short description for the note, or some cute text
 * @param respect A value for how many respect the spider gained after the event
 */
@Serializable

data class Entry (

    /* You know what this is ;) */
    @SerialName(value = "id")
    val id: kotlin.Long? = null,

    /* The date when the experience or note happened */
    @Contextual @SerialName(value = "date")
    val date: java.time.LocalDate? = null,

    /* A short description for the note, or some cute text */
    @SerialName(value = "text")
    val text: kotlin.String? = null,

    /* A value for how many respect the spider gained after the event */
    @SerialName(value = "respect")
    val respect: kotlin.Long? = null

)

