/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.shipi.mylittlespiders.data.network.client.models

import dev.shipi.mylittlespiders.data.network.client.models.Entry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name The name of the friend
 * @param location The room or place where the spider resides in
 * @param nightmares The number of nightmares with the spider
 * @param propertyEntries 
 */
@Serializable

data class Roommate (

    @SerialName(value = "id")
    val id: kotlin.Long? = null,

    /* The name of the friend */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* The room or place where the spider resides in */
    @SerialName(value = "location")
    val location: kotlin.String? = null,

    /* The number of nightmares with the spider */
    @SerialName(value = "nightmares")
    val nightmares: kotlin.Long? = null,

    @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.List<Entry>? = null

)

