/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.shipi.mylittlespiders.data.network.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name The name of the friend
 * @param location The room or place where the spider resides in
 * @param nightmares The number of nightmares with the spider, default is 0
 */
@Serializable

data class RoommateForm (

    /* The name of the friend */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The room or place where the spider resides in */
    @SerialName(value = "location")
    val location: kotlin.String,

    /* The number of nightmares with the spider, default is 0 */
    @SerialName(value = "nightmares")
    val nightmares: kotlin.Long? = 0L

)

